### ISSUE TITLE
Documentation: fix docker-compose.yml

### ISSUE THREAD

**Issue by Mugane** [DanielDent/docker-nginx-ssl-proxy#35]
The documentation should wrap that docker-compose.yml file under `services:` like so:
```
services:
  nginx-ssl-proxy:
    image: danieldent/nginx-ssl-proxy
    restart: always
    environment:
      UPSTREAM: 127.0.0.1:8080
      SERVERNAME: test.example.com
      EXTRANAMES: www.test.example.com,test2.example.com
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - "/etc/letsencrypt"
```
If you don't, you'll get an error such as:
*(root) Additional property nginx-ssl-proxy is not allowed*

Also, `docker-compose up` is deprecated, now it's `docker compose up`
