### ISSUE TITLE
Non-default http ports

### ISSUE THREAD

**Issue by richardhj** [DanielDent/docker-nginx-ssl-proxy#7]
I must not use the default http ports 80 and 443 (it is preserved by macOS Server).
So I've chosen different ports but LetsEncrypt does call port 80: `sslproxy_1      | http://example.org/.well-known/acme-challenge/aQUorM87vM7pFCRxidfmFFzs_n_MqODBW2tFivinYhk:`

```yml
services:
  sslproxy:
    image: danieldent/nginx-ssl-proxy
    restart: always
    environment:
      UPSTREAM: 127.0.0.1:8882
      SERVERNAME: example.org
    ports:
      - "89:80"
      - "442:443"
    volumes:
      - …/docker/nextcloud/nginx-conf:/etc/nginx/conf.d
```
