### ISSUE TITLE
.app domains

### ISSUE THREAD

**Issue by shoooe** [DanielDent/docker-nginx-ssl-proxy#9]
I'm trying to use this docker image likes this:

```
  nginx-ssl-proxy:
    image: danieldent/nginx-ssl-proxy
    environment:
      UPSTREAM: 127.0.0.1:5000
      SERVERNAME: x.app
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - "/etc/letsencrypt"
```

but for my `x.app` domain I get:

> Failed authorization procedure. x.app (http-01): urn:acme:error:unauthorized :: The client lacks sufficient authorization :: Invalid response from http://x.app/.well-known/acme-challenge/Uutj...

I have a feeling this is because `.app` is [one of the first TLDs domains](https://www.zdnet.com/article/google-our-new-app-domain-is-first-to-bake-in-https-to-make-browsing-safer/) with HTTPs "baked in".

Is this true? If so, what can I do to make it work?
